
# Exercise 1: Create a 1D NumPy array of numbers from 0 to 9


In [1]:
import numpy as np

In [2]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


# Exercise 2: Convert 1D array to 2D

Write a code to convert a 1D array to a 2D array with 2 rows.

**Given:**

import numpy as np\
arr = np.arange(6)

**Expected Output:**

Original Array: [0 1 2 3 4 5]\
Reshaped 2x3 Array:\
 [[0 1 2]\
 [3 4 5]]
 

In [7]:
import numpy as np
arr = np.arange(6)

arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])


# Exercise 3: Print Array Attributes

Instructions: Print the following attributes of the array:

The shape of the array.\
The number of array dimensions.\
The size of each element in bytes.\

**Given:**

import numpy as np\
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)

**Expected Output:**

The shape of the array is: (4, 2)\
The number of dimensions is: 2\
The size of each element in bytes is: 2


In [6]:
import numpy as np
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)

print(f"The shape of the array is: {my_array.shape}")
print(f"The number of dimensions is: {my_array.ndim}")
print(f"The size of each element in bytes is: {my_array.itemsize}")

The shape of the array is: (4, 2)
The number of dimensions is: 2
The size of each element in bytes is: 2



# Exercise 6: Create a 1D array filled with zeros and another filled with ones

**Expected Output:**

Zeros: [0. 0. 0. 0. 0.]\
Ones: [1. 1. 1. 1. 1.]


In [9]:
zeros = np.zeros(5)
ones = np.ones(5)

print(f"Zeros: {zeros}")
print(f"Ones: {ones}")

Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]



# Exercise 7: Create a 1D array of 10 evenly spaced values between 5 and 50

**Expected Output:**

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]

In [11]:
np.linspace(5, 50, num=10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

# Exercise 8: Convert a Python list into a NumPy array

**Given:**

py_list = [1, 2, 3, 4, 5]


In [12]:
py_list = [1, 2, 3, 4, 5]
np.array(py_list)

array([1, 2, 3, 4, 5])


# Exercise 9: Find the memory size of a NumPy array of numbers from 0 to 9

**Expected Output:**

Array: [0 1 2 3 4 5 6 7 8 9]\
Memory size in bytes: 80

In [14]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"Array : {arr}")
print(f"Memory size in bytes : {arr.nbytes}")

Array : [0 1 2 3 4 5 6 7 8 9]
Memory size in bytes : 80



# Exercise 10: Reverse a 1D NumPy array

**Given:**

import numpy as np\
arr = np.arange(10)

**Expected Output:**

[9 8 7 6 5 4 3 2 1 0]

In [17]:
import numpy as np
arr = np.arange(10)
arr.sort()
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


# Exercise 11: Create a 3×3 identity matrix

**Expected Output:**

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [18]:
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Exercise 12: Create a 4×4 array and extract its first row and last column

**Expected Output:**

Array:\
 [[ 1  2  3  4]\
 [ 5  6  7  8]\
 [ 9 10 11 12]\
 [13 14 15 16]]
 
First Row: [1 2 3 4]\
Last Column: [ 4  8 12 16]


In [28]:
arr = np.array([
    [ 1,  2,  3,  4,], 
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16,]
])
print(f"First row: {arr[0]}")
print(f"Last Column: {arr[0:4,3]}")

First row: [1 2 3 4]
Last Column: [ 4  8 12 16]



# Exercise 15: Slice the first two rows and first two columns from a 4×4 array

Write a code to Create a 4×4 NumPy array and extract the first two rows and first two columns.

**Expected Output:**

Array:\
 [[ 1  2  3  4]\
 [ 5  6  7  8]\
 [ 9 10 11 12]\
 [13 14 15 16]]
 
First 2 rows and columns:\
 [[1 2]\
 [5 6]]
 

In [29]:
arr = np.array([
    [ 1,  2,  3, 4,],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16]
])

arr[0:2, 0:2]

array([[1, 2],
       [5, 6]])


# Exercise 16: Replace all odd numbers in a NumPy array with -1

**Expected Output:**

Original Array: [ 1  2  3  4  5  6  7  8  9 10]\
Modified Array: [-1  2 -1  4 -1  6 -1  8 -1 10


In [36]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr[arr % 2 != 0] = -1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])


# Exercise 26: Create a random 3×2 matrix and find its maximum and minimum values


In [40]:
arr = np.random.rand(3,2)
print(f"Array: {arr}")
print(f"Max: {arr.max()}")
print(f"Min: {arr.min()}")

Array: [[0.7190484  0.67172224]
 [0.48424098 0.21932809]
 [0.14435809 0.77120265]]
Max: 0.7712026461166896
Min: 0.1443580938374749



# Exercise 27: Sorting a NumPy array based on a specific column

**Given:**

import numpy as np\
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])


In [47]:
import numpy as np
arr = np.array([
    [34, 43, 73], 
    [82, 22, 12], 
    [53, 94, 66]
])

arr[arr[:,1].argsort()]

array([[82, 22, 12],
       [34, 43, 73],
       [53, 94, 66]])


# Exercise 28: Delete and Insert a Column in a NumPy Array

Delete the second column from a given array and insert the following new column in its place.

**Given:**

import numpy as np

sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])\
newColumnToAdd = np.array([10, 10, 10])

**Expected Output:**

[[34 10 73]\
 [82 10 12]\
 [53 10 66]]
 

In [53]:
import numpy as np

arr = np.array([[34,43,73],[82,22,12],[53,94,66]])
newCol = np.array([10, 10, 10])

#take the array, the row/column number, and axis (0 = row, 1 = column)
arr = np.delete(arr, 1, axis=1)

#takes the array, the row/column number, the values to add, axis(0 = row, 1 = column)
arr = np.insert(arr, 1, newCol, axis=1)
arr

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])


# Exercise 29: Swap column 1 and 2 in a 2D array

**Given:**

import numpy as np\
arr = np.arange(9).reshape(3, 3)

The columns are at index 0, 1, 2. We want to rearrange to 0, 2, 1

**Expected Output:**

Before\
[[0 1 2]\
 [3 4 5]\
 [6 7 8]]

After\
[[0 2 1]\
 [3 5 4]\
 [6 8 7]]
 |

In [55]:
import numpy as np
arr = np.arange(9).reshape(3, 3)

arr[:,[1,2]] = arr[:, [2,1]]
arr

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])


# Exercise 30: Generate 10 random integers between 1 and 100


In [61]:
arr = np.random.randint(1, 100, 10)
arr

array([ 8, 27, 20, 85,  7, 74, 77, 76, 48, 93], dtype=int32)


# Exercise 31: Create a 3×3 array of random integers and sort it row-wise


In [68]:
arr = np.random.randint(1, 100, 9).reshape(3,3)
#takes the array and axis(1= row, 0 = column)
np.sort(arr, axis=1)

array([[22, 35, 37],
       [14, 26, 90],
       [53, 74, 84]], dtype=int32)

# Exercise 33: Create a 5×5 2D array with 1s on the border and 0s inside.

**Expected Output:**

[[1. 1. 1. 1. 1.]\
 [1. 0. 0. 0. 1.]\
 [1. 0. 0. 0. 1.]\
 [1. 0. 0. 0. 1.]\
 [1. 1. 1. 1. 1.]]
 

In [12]:
import numpy as np
arr = np.ones((5,5))

arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])


# Exercise 35: Sort the rows of a 2D array based on the values of the second column

**Given:**

import numpy as np\
arr = np.array([[8, 4, 1],\
                [5, 2, 7],\
                [6, 9, 3]])
                
**Expected Output:**

[[5 2 7]\
 [8 4 1]\
 [6 9 3]]
 

In [13]:
import numpy as np
arr = np.array([[8, 4, 1],
                [5, 2, 7],
                [6, 9, 3]])

arr = arr[arr[:, 1].argsort()]
arr

array([[5, 2, 7],
       [8, 4, 1],
       [6, 9, 3]])


# Exercise 36: Flatten a multi-dimensional NumPy array

Write a code to Convert a 2D array into a 1D array.

**Given:**

import numpy as np\
arr = np.array([[1, 2], [3, 4], [5, 6]])


In [14]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6]])

arr.flatten()

array([1, 2, 3, 4, 5, 6])


# Exercise 37: Stack two arrays vertically and horizontally

**Given:**

import numpy as np\
a = np.array([1, 2, 3])\
b = np.array([4, 5, 6])

In [19]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.hstack((a,b)))
print(np.vstack((a,b)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# Exercise 39: Perform Addition and Squaring on Arrays

**Given:**

import numpy as np\
arrayOne = np.array([[5, 6, 9], [21, 18, 27]])\
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

**Expected Output:**

Result of array addition:\
[[20 39 33]\
 [25 25 28]]

Result with each element squared:\
[[ 400 1521 1089]\
 [ 625  625  784]]


In [22]:
import numpy as np
arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])
addArr = np.add(arrayOne, arrayTwo)
print(f"Result of array addition: \n{addArr}")
print(f"Result of square of addition array: \n{np.square(addArr)}")


Result of array addition: 
[[20 39 33]
 [25 25 28]]
Result of square of addition array: 
[[ 400 1521 1089]
 [ 625  625  784]]



# Exercise 40: Invert a matrix

**Given:**

import numpy as np\
arr = np.array([[1, 2], [3, 4]])

**Expected Output:**

[[-2.   1. ]\
 [ 1.5 -0.5]]
 

In [25]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])

np.linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])


# Exercise 41: Use boolean indexing to filter values less than a given number

From an array, return values less than 30.

**Given:**

import numpy as np\
arr = np.array([5, 12, 29, 30, 44, 7, 18])


In [26]:
import numpy as np
arr = np.array([5, 12, 29, 30, 44, 7, 18])

arr[arr < 30]

array([ 5, 12, 29,  7, 18])


# Exercise 42: Count the number of occurrences of each unique element

**Given:**

import numpy as np\
arr = np.array([2, 3, 2, 5, 3, 3, 2, 5])


In [37]:
import numpy as np
arr = np.array([2, 3, 2, 5, 3, 3, 2, 5])

unique, counts = np.unique(arr, return_counts=True)
print(f"Value {unique[0]} occurs {counts[0]} time(s)")
print(f"Value {unique[1]} occurs {counts[1]} time(s)")
print(f"Value {unique[2]} occurs {counts[2]} time(s)")

Value 2 occurs 3 time(s)
Value 3 occurs 3 time(s)
Value 5 occurs 2 time(s)



# Exercise 43: Find the intersection and union of two arrays

Intersection: elements present in both arrays.\
Union: all unique elements from both arrays, sorted.

**Given:**

import numpy as np\
a = np.array([1, 2, 3, 5, 7])\
b = np.array([3, 4, 5, 6, 7])


In [39]:
import numpy as np
a = np.array([1, 2, 3, 5, 7])
b = np.array([3, 4, 5, 6, 7])

print(f"Intersection: {np.intersect1d(a,b)}")
print(f"Intersection: {np.union1d(a,b)}")

Intersection: [3 5 7]
Intersection: [1 2 3 4 5 6 7]



# Exercise 44: Transpose a matrix

Transposing a matrix means flipping it over its diagonal.

**Given:**

import numpy as np\
arr = np.array([[1, 2], [3, 4]])


In [40]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])

arr.T

array([[1, 3],
       [2, 4]])


# Exercise 45: Compute the eigenvalues and eigenvectors of a matrix

For a square matrix, compute its eigenvalues and eigenvectors.

**Given:**

import numpy as np\
A = np.array([[4, 2],\
              [1, 3]])
              

In [44]:
import numpy as np
A = np.array([[4, 2],
              [1, 3]])

np.linalg.eig(A)

EigResult(eigenvalues=array([5., 2.]), eigenvectors=array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]]))


# Exercise 46: Solve a linear equation

Solve the system of linear equations: x + 2y = 8 and 3x + 4y = 18.


In [45]:
A = np.array([
    [1,2],
    [3,4]
])

b = np.array([8,18])

np.linalg.solve(A, b)

array([2., 3.])


# Exercise 48: Find nearest value

Find the value in an array that is closest to a number 3.

**Given:**

import numpy as np\
arr = np.array([1.5, 2.8, 3.2, 4.1])


In [46]:
import numpy as np
arr = np.array([1.5, 2.8, 3.2, 4.1])
target = 3
index = np.abs(arr - target).argmin()

arr[index]

np.float64(2.8)